import type { Metadata } from 'next';
import AppLink from './components/AppLink';
import './globals.css';
import layout from './layout.module.css';

export const metadata: Metadata = {
  title: "Kirill's games",
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={layout.app}>
        <aside className={layout.aside}>
          <AppLink href="tetris">Tetris</AppLink>
          <AppLink href="snake">Snake</AppLink>
          <AppLink href="tick-tack-toe">Tick Tack Toe</AppLink>
          <AppLink href="2048-game">2048</AppLink>
        </aside>
        <main className={layout.page}>{children}</main>
      </body>
    </html>
  );
}
